CREATE TABLE "fotos_clinicas" (
  "id_foto" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_clinica" INT NOT NULL,
  "titulo" VARCHAR(100) NOT NULL,
  "url" VARCHAR(500) NOT NULL,
  "tipo" VARCHAR(50) NOT NULL,
  "es_principal" BOOLEAN DEFAULT FALSE,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Add foreign key constraint
ALTER TABLE "fotos_clinicas" ADD FOREIGN KEY ("id_clinica") REFERENCES "clinicas" ("id_clinica") ON DELETE CASCADE;

-- Add index for faster queries
CREATE INDEX idx_fotos_clinicas_id_clinica ON "fotos_clinicas" ("id_clinica");
CREATE INDEX idx_fotos_clinicas_tipo ON "fotos_clinicas" ("tipo");
CREATE INDEX idx_fotos_clinicas_es_principal ON "fotos_clinicas" ("es_principal");

-- Add trigger for automatic updated_at column update
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = now(); 
   RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_fotos_clinicas_modtime
BEFORE UPDATE ON "fotos_clinicas"
FOR EACH ROW
EXECUTE FUNCTION update_modified_column();